version: "3.9"

services:
  app:
    build: .
    networks:
      - common_network
  mailhog:
    image: mailhog/mailhog
    networks:
      - common_network
    logging:
      driver: "none"
    ports:
      - "1025:1025" # SMTP Server
      - "8025:8025" # WebUI

networks:
  common_network:
    external: true
    name: common_network