version: "3.9"

services:
  app:
    build: .
    restart: always
    networks:
      - common_network
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:

networks:
  common_network:
    external: true
